docker:
  host: unix:///var/run/docker.sock
  tls-verify: false
  registry-url: https://index.docker.io/v1/1
  containers:
    redis:
      enabled: true
      container-name: redis-container
      image-name: redis:latest
      ports:
        6379: 6379